create database users;
use users;
show databases;
create table user (uid int, uname string, upwd string);
create table customer (cid int, cname string, cemail string);
create table product (pid int, pname string, price float);
create table order_table (oid int, uid int, total float);
create table employee (eid int, ename string, department string);
create table supplier (sid int, sname string, contact string);
create table category (catid int, catname string, description string);
create table inventory (inv_id int, pid int, quantity int);
create table payment (pay_id int, oid int, amount float, method string);
create table shipping (ship_id int, oid int, address string, status string);
create table review (review_id int, pid int, uid int, rating int, comment string);
create table wishlist (wish_id int, uid int, pid int);
create table cart (cart_id int, uid int, pid int, quantity int);
create table invoice (invoice_id int, oid int, total float, date string);
create table refund (refund_id int, oid int, amount float, reason string);
create table 用户 (用户ID int, 用户名 string, 用户密码 string);
create table 订单 (订单ID int, 用户ID int, 总金额 float);
create table 商品 (商品ID int, 商品名 string, 价格 float);
create table 员工 (员工ID int, 员工名 string, 部门 string);
create table 供应商 (供应商ID int, 供应商名 string, 联系人 string);
create table 分类 (分类ID int, 分类名 string, 描述 string);
create table 库存 (库存ID int, 商品ID int, 数量 int);
create table 支付 (支付ID int, 订单ID int, 金额 float, 方式 string);
create table 配送 (配送ID int, 订单ID int, 地址 string, 状态 string);
create table 评价 (评价ID int, 商品ID int, 用户ID int, 评分 int, 评论 string);
create table 收藏 (收藏ID int, 用户ID int, 商品ID int);
create table 购物车 (购物车ID int, 用户ID int, 商品ID int, 数量 int);
create table 发票 (发票ID int, 订单ID int, 总金额 float, 日期 string);
create table 退款 (退款ID int, 订单ID int, 金额 float, 原因 string);
show tables;
show struct 用户;
show struct product;
quit;
